### ISSUE TITLE
Translation for plugins in control panel

### ISSUE THREAD

**Issue by Djive** [enupal/translate#14]
Not sure if this is duplicate of this: https://github.com/enupal/translate/issues/1

For testing purposes I translated one plugin through Enupal translate plugin.
It created the translated file but the translated plugin didnt change language in control panel.
I copied this file from plugin folder to /translations/lang-code folder.
But I still don't get anything translated when i visit the translated plugin in control panel.

How can I achieve this?

Thanks in advance for any info!

- Craft version: 3.0.27
- PHP version: 7.2.6
- Database driver & version: MySQL 5.6.38
- Plugin version: 1.1.3

**Comment by andrelopez** [comment]
Hi @Djive 

This issue is solved in v1.1.4 Could you please update the plugin and let us know if that solves the issue?

Best

**Comment by andrelopez** [comment]
Hi @Djive 

Could you please share us the translation tag used in your plugin templates? Remember to use the handle of your plugin e.g

`{{ 'Hello world'|t('plugin-handle') }}`

**Comment by Djive** [comment]
Everything is working ok. 
We had EN as the set language in Control Panel because our lanugage is not supported.
Thats why nothing was showing.

Thanks!
