### ISSUE TITLE
CMD + S not working

### ISSUE THREAD

**Issue by kaspar-allenbach** [enupal/translate#15]
Thats just a tiny detail: In you plugin it is not possible to save via `CMD + S` or `CTRL + S` on windows, like in the rest of craft.

**Comment by andrelopez** [comment]
Thanks for reporting, I'm on it!

**Comment by andrelopez** [comment]
Hi @kaspar-allenbach 

We just released Enupal Translate v1.1.6 with a fix for this bug 

Best,
