### ISSUE TITLE
usergroup restricted to one site can't save translations unless you click the dropdown again

### ISSUE THREAD

**Issue by jhealey5** [enupal/translate#16]
### Description
We have a multisite with a number of user-groups for translators. Each group is assigned to a language and that language only. If that user-group tries to make a translation through enupal, it doesn't save (even after waiting for the delay/refreshing).

It appears to fix it if you click the dropdown and select the language again. Or if you assign the default site to that group too.

### Steps to reproduce

1. Create a user-group with permissions to only edit enupal and a site other than the default site.
2. Edit a template string - no save?
3. Click the dropdown and select the current language again.
4. Edit a template string - save?

### Additional info

- Craft version: 3.0.23.1
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.24
- Plugin version: 1.1.5

**Comment by andrelopez** [comment]
Hi @jhealey5 

I'll try to recreate this issue and I'll let you know if I have any questions.

Best,

**Comment by andrelopez** [comment]
Hi @jhealey5 

We just released Enupal Translate v1.1.6 with a fix for this bug and also "CMD+S" support
