### ISSUE TITLE
Plugin thinks variable is translation string

### ISSUE THREAD

**Issue by piotrpog** [enupal/translate#18]
This piece of code:
```
    {% if prev %}<a href="{{prev.url}}" class="button">{{'previous_post'|t}} {{prev.title}}</a>{% endif %}
    {% if next %}<a href="{{next.url}}" class="button">{{'next_post'|t}} {{next.title}}</a>{% endif %}
```
Causes `{{prev.url}}` and `{{next.url}}` appear on translation string list.

**Comment by andrelopez** [comment]
Hi @piotrpog 

This issue is solved in Enupal Translate v1.2.0

You'll need to update the `Twig search method` setting under `Enupal Translate -> Settings -> General` to use the `Optimized search method`.

More info [here](https://github.com/enupal/translate/issues/19#issuecomment-457938150)
