### ISSUE TITLE
Loading template translations failed

### ISSUE THREAD

**Issue by bertoost** [enupal/translate#2]
When clicking a template, I'll receive this error;

![image](https://user-images.githubusercontent.com/398492/39970626-00a081da-56ef-11e8-8e3a-927c29b3d2c2.png)

The AJAX response is;
Forbidden: User not permitted to access this source

What could this be?

**Comment by andrelopez** [comment]
Hi @bertoost 

Could you please confirm that you have more than one site on you Craft CMS setup?
Also, this error comes up specifically with the _details.html.twig_ template ?

Best

**Comment by bertoost** [comment]
Hi @andrelopez 
I have configured multiple websites. They are not yet working, but I defined them already.
And it's not coming from the previewed template. All templates show that error
Thanks!
Regards, Bert

**Comment by andrelopez** [comment]
The error message says something about permissions. @bertoost Have you logged in as an admin?

I'm still unable to recreate this issue

**Comment by bertoost** [comment]
Maybe that’s because I am running sites in Docker. The php container is different than the Nginx web server of course. I will try to figure that out.

**Comment by andrelopez** [comment]
Hi @bertoost 

We just released v1.1.0 could you please upgrade and check if the issue is solved?

Best,

**Comment by andrelopez** [comment]
Hey @bertoost 

I was able to recreate this issue and should be fixed in the latest version V 1.1.1

Please let me know if works for you.

Best

**Comment by bertoost** [comment]
Thanks guys! I am not (yet) actively using it. Will try it out next few days.
