### ISSUE TITLE
Plugin incompatible with load balanced environments

### ISSUE THREAD

**Issue by gijsstegehuis** [enupal/translate#22]
Due to the current nature of this plugin it's impossible to run it in a load balanced environment.
e.g. the translations file will get updated on serverX but not on serverY, thus only showing the correct translations on serverX.

A possible solution to this would be to store the translation rows in a database and then write a new translation file every time the rows are changed. This also requires a console command to trigger this action when the Craft app is deployed.

Check the link below to see how @boboldehampsink did this in a similar plugin for Craft 2:
https://github.com/boboldehampsink/translate/blob/master/services/TranslateService.php#L75

**Comment by andrelopez** [comment]
Hi @gijsstegehuis 

We recommend installing [Enupal Backup](http://plugins.craftcms.com/enupal-backup) to backup the translations files when your site goes live.

**Comment by gijsstegehuis** [comment]
Hi @andrelopez. I am not sure how that's going the fix the problem i described.
Can you explain what you mean exactly?

**Comment by boboldehampsink** [comment]
fwiw: my plugin was incompatible with load balanced environments as well and worked the same way this plugin does.

**Comment by gijsstegehuis** [comment]
Ah yeah, mixed some plugins up i guess.
The proposed solution above, however, could still work.

**Comment by missmatsuko** [comment]
I didn't realize until today that this plugin only generates the translation files. I expected it to store user-entered translations in the database. Probably not going to use it in a production environment since I'm worried the translation file will get out of sync or get deleted, etc.

**Comment by andrelopez** [comment]
Hi @missmatsuko @gijsstegehuis @boboldehampsink  We just released Enupal Translate v2.0.0 with support to sync your translations into the DB more info here https://docs.enupal.com/translate/translate/sync-with-db.html Please let me know if you have any questions
