### ISSUE TITLE
Incorrect detection of translation string

### ISSUE THREAD

**Issue by piotrpog** [enupal/translate#26]
I have such Twig code:
```
{% include '_svg/arrow.svg' %}{{'side_search'|t}}
```
Enupal translate shows `_svg/arrow.svg` as translation string instead `side_search`.

**Comment by andrelopez** [comment]
Hi @piotrpog 

Could you please go to Enupal Translate -> Settings and set the "Twig search method" to `Optimized twig search method` Save your settings and see if that solves the problem?

Best,
