### ISSUE TITLE
Google Translate Free gives 404 error 

### ISSUE THREAD

**Issue by TomDeSmet** [enupal/translate#28]
Maybe the URL needs adjusting? The Google Translate Free option gives a 404 error.

`Client error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=nl&tl=fr&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=108424.496886` resulted in a `400 Bad Request` response:`

**Comment by andrelopez** [comment]
Hi @TomDeSmet We just released Enupal Translate v1.2.1 with a fix to this issue. Thank you.
