### ISSUE TITLE
Import as CSV possible?

### ISSUE THREAD

**Issue by stenvdb** [enupal/translate#3]
I'm curious, I see there's a download as CSV option, but it is also possible to import your translations in bulk as CSV?

Notify 

- [x] [1543418451517100001](https://mail.zoho.com/zm/#mail/folder/inbox/p/1543418451517100001)

**Comment by andrelopez** [comment]
Hi @stenvdb we'll add this feature in the next release.

Best,

**Comment by andrelopez** [comment]
Hi @stenvdb 

We just released Enupal Translate v1.1.7 and added support for import CSV files.

Best
