### ISSUE TITLE
Cannot Install on Craft 3.4.9

### ISSUE THREAD

**Issue by CreateSean** [enupal/translate#30]
### Description
I tried to install this via the command line and got the following errors:

 Problem 1
    - enupal/translate 1.2.0 requires viniciusgava/google-translate-api 2.0.2 -> satisfiable by viniciusgava/google-translate-api[2.0.2].
    - Installation request for enupal/translate ^1.2 -> satisfiable by enupal/translate[1.2.0].
    - Conclusion: remove guzzlehttp/guzzle 6.5.2
    - Conclusion: don't install guzzlehttp/guzzle 6.5.2
    - viniciusgava/google-translate-api 2.0.2 requires guzzlehttp/guzzle ~6.3.0 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 6.5.2].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 6.5.2].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 6.5.2].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 6.5.2].
    - Installation request for guzzlehttp/guzzle (locked at 6.5.2) -> satisfiable by guzzlehttp/guzzle[6.5.2].

### Steps to reproduce

1. try to install enupal translate on craft 3.4.9
2.

### Additional info

- Craft version:3.4.9
- PHP version: 7.2.28
- Database driver & version: mysql 5.5.5
- Plugin version:

**Comment by andrelopez** [comment]
Hi @CreateSean Could you please send back to us the list of plugins that you have installed to support@enupal.com? It looks like there is a conflict with one of them

**Comment by CreateSean** [comment]
@andrelopez 

Feed Me
Field Manager
Freeform
Gravatar
Imager (will be switching to imager x soon)
Linkit
Position Fieldtype
Redactor
Retcon
SEOmatic
Super Table
Template Comments
User manual
Video embedder
Wordsmith

**Comment by CreateSean** [comment]
so still can't install this plugin due to the guzzle issue

**Comment by andrelopez** [comment]
Hi @CreateSean We just released Enupal Translate v1.2.2 with a possible fix to this issue. Please let me know how it goes.

Best,

**Comment by CreateSean** [comment]
@andrelopez Yes I'm good now. Thank you.
