### ISSUE TITLE
Translations don't save in Craft 3.4.5; 404 error in logs

### ISSUE THREAD

**Issue by michaelhartford** [enupal/translate#31]
### Description
We recently updated to Craft 3.4.5 from 3.1. We are unable to save translations in the Enupal plugin; the "Translation Saved" message is displayed, but the text reverts to the previous value and the translated text is not rendered on the site.

In the web-404s.log file, I see this error:
HttpException: Template not found: bisg/sisac.html in /var/www/infor.com/prod/vendor/craftcms/cms/src/controllers/TemplatesController.php:90

### Steps to reproduce

1. In Craft web console, go to Enupal Translate \ Translations
2. Select "Pending" under "Template Status"
3. Select a sub-site from the "Translate to" drop down
4. Update the text in one of the "Translation" fields
5. Click "Save"; observe that the "Translations saved" message is displayed
6. Observe that the updated text has reverted to the previous value

### Additional info

- Craft version: Craft Pro 3.4.5
- PHP version: 7.1.30
- Database driver & version: MySQL 5.6.39
- Plugin version: 1.2.0

**Comment by andrelopez** [comment]
Hi @michaelhartford What is your Twig search method? you can check that setting going to Enupal Translate -> Settings

**Comment by michaelhartford** [comment]
“Legacy twig search method”

**Comment by andrelopez** [comment]
Could you please update to "Optimized twig search method" ? If the error persists could you please recreate the error and send back to us a zip file of the following folder? `storage/logs` to support@enupal.com

**Comment by michaelhartford** [comment]
My email with the logs attached was rejected as the file size exceeded the receiving system’s limits. I’ve uploaded the logs to a Google URL here:


If you’re not able to download, let me know and I can zip up just the files that you need to review.

Thanks!
----

I made the change to “Optimized twig search method” in our stage environment, as the logs should be less noisy there, and the problem still occurs. I’ve attached the contents of the logs folder to this email.

Thanks!

**Comment by andrelopez** [comment]
@michaelhartford I'll do some debugging from here

**Comment by michaelhartford** [comment]
My end user reports " ... nothing shows under the Translated section of Enupal Translate for any site now. The words still appear to be translated on the site, but no translations show at all." She's unable to add new translations for sites that are scheduled to come on line in the next month.

**Comment by michaelhartford** [comment]
End user is reporting that translated text is now not showing on previously translated pages (this may have been missed after the initial upgrade because of the edge server caching we do); this issue has become much more urgent for us. Is there anything we can do to assist in finding a solution? This is the report I just received:


Hi Michael Hartford unfortunately this has   become more urgent. It appears the plugin HAS erased all the translations   it stored across every regional site. Unlike I previously thought.   While I checked these when I submitted the   ticket, by now it seems like the cache has finally expired and I'm suddenly   seeing phrases I know used to be in Enupal Translate, but now in English.       France Events page – https://www.infor.com/fr-fr/events         Upcoming Events, View All Events, etc – used to be French    Mexico Resources page – https://www.infor.com/es-mx/resources         Filter By, View All, All Industries, etc – used to be Spanish          (note, you'll see a few small headers in Spanish still, those are        categories of assets so those translations are stored elsewhere)    Netherlands blog page – https://www.infor.com/nl-nl/blog         Search the blog, All Industries, etc – used to be Dutch    Japan news page – https://www.infor.com/ja-jp/news         Search All News, Filter By, etc – used to be Japanese      Therefore all regional sites are now showing   some English on at least the Events, Blog, Resources, and News pages.   Probably others but again, can't be sure where all Enupal Translate   translations were being used.       Vic Shoup CCing you for visibility on   this issue in case Field Marketing reports noticing it. You can see above,   Michael is investigating the fact that a Craft plugin that stores some of the   minor site translations apparently stopped working, presumably as a result of   the upgrade. Those words appear to have reverted back to English (default).
--

**Comment by andrelopez** [comment]
Hi @michaelhartford Could you please follow up via email support@enupal.com ?

**Comment by michaelhartford** [comment]
Closing the loop on this one, as it turns out to have been a problem with a different plugin:

The Acclaro Translations plugin had a namespace conflict with Craft's static translations loading, preventing the translations from being loaded from the /translations/[lang]/site.php files. Enupal was showing the English text for all translations because it wasn't able to load the translations from the files, and when a user saved translations through Enupal the previous translations were overwritten in the file if they weren't also included on the web form.

This issue can be closed from the Enupal side; it has been addressed in Acclaro Translations 1.6.0

https://github.com/AcclaroInc/craft-translations/issues/57

Thanks!

**Comment by andrelopez** [comment]
@michaelhartford Thank you for the update
