### ISSUE TITLE
RFC - Different storage method

### ISSUE THREAD

**Issue by lenvanessen** [enupal/translate#34]
### Description
We love the functionality of this extension. But a lot of our projects are hosted on heroku, meaning anything not in git will be removed upon deployment and generally the client does the translations not the production.

So it would be great if there is an alternative way of storing the translations (DB/S3) so they remain there in between deployments.

**Comment by CreateSean** [comment]
I was just coming here to make the same request.

I expected that copying the database from live to local would get me the translations. But no, I had to ftp the translations folder down and make sure it was gitignored in the future.

**Comment by andrelopez** [comment]
This is for sure our more requested feature, I'll look into this and will back with any update

**Comment by andrelopez** [comment]
Hi @CreateSean @lenvanessen We just released Enupal Translate v2.0.0 with support to sync your translations into the DB more info here https://docs.enupal.com/translate/translate/sync-with-db.html
