### ISSUE TITLE
Can't install v2.2.0 on Craft CMS 3.6.11.2

### ISSUE THREAD

**Issue by pvaessen** [enupal/translate#45]
When trying to do a "craft update enupal-translate" I'm getting the following error:

Output:
================
Yii Migration Tool (based on Yii v2.0.41.1)

Total 1 new Enupal Translate migration to be applied:
    - m210410_000000_add_message_pk

*** applying m210410_000000_add_message_pk
    > add primary key pk_bbyiihkbgtpqxqyiwokxivlmwowvmezerxga on {{%enupaltranslate_message}} (id) ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '53' for key 'PRIMARY'
The SQL being executed was: ALTER TABLE `enupaltranslate_message` ADD CONSTRAINT `pk_bbyiihkbgtpqxqyiwokxivlmwowvmezerxga` PRIMARY KEY (`id`) (C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\db\Schema.php:678)
#0 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\db\Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `en...')
#1 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\db\Command.php(1099): yii\db\Command->internalExecute('ALTER TABLE `en...')
#2 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\db\Migration.php(437): yii\db\Command->execute()
#3 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\craftcms\cms\src\db\Migration.php(363): yii\db\Migration->addPrimaryKey('pk_bbyiihkbgtpq...', '{{%enupaltransl...', 'id')
#4 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\enupal\translate\src\migrations\m210410_000000_add_message_pk.php(20): craft\db\Migration->addPrimaryKey('pk_bbyiihkbgtpq...', '{{%enupaltransl...', 'id')
#5 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\craftcms\cms\src\db\Migration.php(52): enupal\translate\migrations\m210410_000000_add_message_pk->safeUp()
#6 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(744): craft\db\Migration->up()
#7 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\craftcms\cms\src\console\controllers\MigrateController.php(374): yii\console\controllers\BaseMigrateController->migrateUp('m210410_000000_...')
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#10 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\base\Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#11 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\console\Controller.php(184): yii\base\Controller->runAction('all', Array)
#12 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\base\Module.php(534): yii\console\Controller->runAction('all', Array)
#13 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\console\Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#14 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\craftcms\cms\src\console\Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#15 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\console\Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#16 C:\Apache2.4.37\htdocs\inforupgrade13july2020\vendor\yiisoft\yii2\base\Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 C:\Apache2.4.37\htdocs\inforupgrade13july2020\craft(22): yii\base\Application->run()
#18 {main}
*** failed to apply m210410_000000_add_message_pk (time: 0.438s)

0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.

### Additional info

- Craft version: 3.6.11.2
- PHP version: 7.3.1
- Database driver & version: MySQL 8.0.17
- Plugin version: 2.0.0

**Comment by andrelopez** [comment]
@pvaessen Sorry about this issue, please update to Enupal Translate v2.2.1 and let us know how it goes.
