### ISSUE TITLE
Question: Does this work for Entry / fields content?

### ISSUE THREAD

**Issue by RickKukiela** [enupal/translate#48]
I am quoting a  project that needs to use google translate api for translations in 4-5 languages. I see this will work for static template text that needs to be translated, however, what about entry fields? Normally when you have different "language" sites set up in craft, when editing an entry you can switch between languages and fill out the fields in the various languages. Does this plugin provide a way to update entry fields that are blank in various languages as well?

**Comment by andrelopez** [comment]
Hi @RickKukiela Sorry we don't support field types at the moment.
