### ISSUE TITLE
{{ "now"|date('Y') }} gets translated too as "now"

### ISSUE THREAD

**Issue by frontedbe** [enupal/translate#5]
### Description

[view image](https://cl.ly/sgBj)

### Steps to reproduce

1. add {{ "now"|date('Y') }} somewhere
2. Check the Translate plugin for the "now" occurrence

### Additional info

- Craft version: Craft CMS 3.0.13.2
- PHP version: 7.1.16
- Database driver & version: MariaDB stable 10.3.7
- Plugin version: 1.1.0

**Comment by frontedbe** [comment]
Hey there,

Experiencing same type of issue with craft.entries.section('xxx').all() where the 'xxx' shows up in the Translations plugin. Any idea wether it could and/or when will be fixed? Thanks!
I attached a screenshot to illustrate the issue => [view screenshot](https://cl.ly/1a1a80e48e28)

**Comment by piotrpog** [comment]
Yep, I also got it, just used
`{{ 'now'|date('Y') }}`

**Comment by andrelopez** [comment]
Hi @mdominguez 

This issue is solved in Enupal Translate v1.2.0

You'll need to update the `Twig search method` setting under `Enupal Translate -> Settings -> General` to use the `Optimized search method`.

More info [here](https://github.com/enupal/translate/issues/19#issuecomment-457938150)
