### ISSUE TITLE
Question: Is there a way programatically run "Sync with DB"?

### ISSUE THREAD

**Issue by circa1983** [enupal/translate#51]
### Description

Is there a way to programatically run “Sync with DB” via craft cli (console command) or via a shell or php script?

We host our sites on [Servd](https://servd.host/), which uses atomic deployment for all of its sites, this means whenever we update anything (Craft version, plugin updates, template changes, etc), a new environment is created and our static translations are lost! 

Enupal Translate’s brilliant feature “Sync with DB” fixes this, allowing us to apply the static translations to the new instance but it’s a manual step. This means sites that have been automatically updated don’t have the static translations and if the sync isn’t performed before the next deployment, we totally loose the translations.

Servd offers “Post Deploy Tasks” so if you have a Custom Console Command specific to the enupal-translate plugin that would be ideal! 

Failing that, a method which we could access via a module (so we can to create a console command our selves) would suffice.

Many thanks, Sam.

### Additional info

- Craft version: Craft Pro 3.7.29
- PHP version:	 7.4.26
- Database driver & version: 	MySQL 5.5.5
- Plugin version: 2.3.0

**Comment by andrelopez** [comment]
Hi @circa1983 Thanks for reaching out. The following line will add the translate sync to the job queue

```php
use enupal\translate\Translate;
...


Translate::$app->translate->runSync();
```

_Make sure to run `queue/run` [console command ](https://craftcms.com/docs/3.x/console-commands.html#queue-run)to make sure the job is executed_

**Comment by circa1983** [comment]
Hi @andrelopez,

Many thanks for the fast response and thank you for the code snippet, it’s really helpful.

**Comment by tibbis** [comment]
@circa1983 Hi, how did you setup this with **servd** regarding the translations folder, gitignore and workflow commands? I'm having problems with the syncing after switching to this plugin.
