### ISSUE TITLE
SQL Error on install:  create table {{%enupaltranslate_message}} Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.

### ISSUE THREAD

**Issue by adrianjean** [enupal/translate#56]
### Description

I use Digital Ocean managed databases and by default the `sql_require_primary_key` setting is `on`.  When installing this plugin, the installation fails because there seems to be on primary key in a DB entry required on install of this plugin.

Here is the error returned:
```
> create table {{%enupaltranslate_message}} ...Exception: SQLSTATE[HY000]: General error: 3750 Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid thi$

The SQL being executed was: CREATE TABLE `enupaltranslate_message` (
        `id` int(11) NOT NULL,
        `language` varchar(255),
        `translation` text,
        `dateCreated` datetime(0) NOT NULL,
        `dateUpdated` datetime(0) NOT NULL,
        `uid` char(36) NOT NULL DEFAULT '0'
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE = utf8_unicode_ci (/mnt/volume_tor1_01/www/craft/marksutcliffe.ca/vendor/yiisoft/yii2/db/Schema.php:676)

```
### Possible Solutions?

A. Add a primary key to the SQL install
B. Add some SQL to the header of the plugin install SQL script: `SET SQL_REQUIRE_PRIMARY_KEY = 0;`

### Additional info

- Craft version: 3.7.47.1
- PHP version: 7.4.30
- Database driver & version: MySQL 8.0.28
- Plugin version: 2.3.0

**Comment by andrelopez** [comment]
Hi @adrianjean We just released Enupal Translate v2.3.1 with a fix to this error, please let me know how it goes
