### ISSUE TITLE
Db sync to translation files -Enupal Translate Craft Command

### ISSUE THREAD

**Issue by driesbonte** [enupal/translate#61]
### Description
Hi, is there a reverse way to sync db to the php files?
My client has a setup where on every deploy a new server is being created.
Since the translation folder are in the gitignore the translation they don't get to the new environment. 
It would be nice to generate these translate files on the basis of the db on next deploy. 

Thanks

**Comment by andrelopez** [comment]
Hi @driesbonte Here is the info on how to manually sync generate the translate files from the db: https://docs.enupal.com/translate/translate/sync-with-db.html#how-to-sync-translations-into-a-new-environment

For CICD if you run [this line of code ](https://github.com/enupal/translate/blob/master/src/controllers/TranslateController.php#L146) somewhere (like a custom plugin creating a [console command](https://craftcms.com/docs/3.x/console-commands.html)) it will add the sync job to the queue

**Comment by andrelopez** [comment]
Hi @driesbonte Enupal Translate v3.1.0 now supports the `enupal-translate/translate/sync` craft command
