### ISSUE TITLE
Error since upgrade to Craft 4.5

### ISSUE THREAD

**Issue by robin-braibant-alpine** [enupal/translate#64]
### Description
Error since update to Craft 4.5. 
The error occurs because of a type error in `/enupal/translate/src/services/Translate.php` in the `_processFile` function. 
The params are defined as `null`, but the function needs an array.
`$translation = Craft::t($category, $original, null, $site->language);`

=> this fixes it: `$translation = Craft::t($category, $original, [], $site->language);`

### Steps to reproduce

1. Upgrade to Craft 4.5
2. Open the plugin

### Additional info

- Craft version: 4.5.2
- PHP version: 8.1
- Database driver & version: MySql 5.7.34
- Plugin version: 3.0.1

**Comment by benoitblancquaert** [comment]
I have this problem with version 4.5 as well.

**Comment by belkin** [comment]
Is there any update on this? We're getting same problem on 4.5.2.

**Comment by andrelopez** [comment]
Thanks for reporting this one we're working on it

**Comment by andrelopez** [comment]
We just released Enupal Translate v3.1.0 with a fix to this issue. Thanks for reporting
