### ISSUE TITLE
Craft 5 - error on sitehandle when using only one site

### ISSUE THREAD

**Issue by robin-braibant-alpine** [enupal/translate#68]
### Description
We upgraded our project from Craft 4 to Craft 5. Our project only has one site. When opening the `Translations` menu item of the plugin, the following errors occurs:
<img width="1361" alt="image" src="https://github.com/enupal/translate/assets/117266131/7274b5ee-1370-4a40-b2cd-897ebd671b48">
The error gets thrown in the `src/templates/index.twig` file of the plugin. You are checking for a parameter, but when only one site is available, the site is parameter is not present.

### Steps to reproduce

1. Install plugin in Craft 5 project with one site
2. Try to open the translations

### Additional info

- Craft version: Solo 5.1.5
- PHP version: 8.2.8
- Database driver & version: MySql 8.0.33
- Plugin version: 4.0.1

**Comment by robin-braibant-alpine** [comment]
@andrelopez 
Can you come back on this issue please?

**Comment by andrelopez** [comment]
Hi @alpine-digital we just released v4.0.2 with a fix to this issue. Thanks for reporting
