### ISSUE TITLE
Possibility to change plugin name in admin panel

### ISSUE THREAD

**Issue by jan-dh** [enupal/translate#7]
### Description
Would be nice to give a custom name to the plugin in the admin panel. Makes it easier to find for customers.

**Comment by andrelopez** [comment]
Hi @jan-dh, this feature will be available in the next release. I'll let you know when is released.

**Comment by jan-dh** [comment]
Nice, thanks for the quick reply!

**Comment by andrelopez** [comment]
Hi @jan-dh 

This feature is added in v1.1.3 you can override the plugin name in the General settings of the plugin,

Best,
