### ISSUE TITLE
[Craft 5] Translation keys are not visible

### ISSUE THREAD

**Issue by svondervoort** [enupal/translate#71]
### Description
The left column seems to be empty, it is not showing the translation keys as it was in previous versions. I'm not sure if this is a Craft 5 / Enupal 4 issue since this is the first time we are setting up a Craft 5 site. 

![image](https://github.com/user-attachments/assets/8a53a678-9cb5-43be-a87c-85fa955269de)

### Steps to reproduce

1. Create a Craft 5 site
2. Add a translation to a template
3. Go to the Enupal Translate plugin

### Additional info

- Craft version: 5.2.8
- PHP version: 8.3
- Database driver & version:
- Plugin version: 4.0.2

**Comment by belkin** [comment]
We are seeing the same problem with Craft 5.3.2 and Enupal Translate 4.0.2.

**Comment by andrelopez** [comment]
Thanks for reporting, looking into this now

**Comment by andrelopez** [comment]
We just released Enupal Translate v4.0.3 with a fix to this issue. Thanks for reporting!

**Comment by svondervoort** [comment]
Yes they are working again, thanks!
