### ISSUE TITLE
Nothing showing up

### ISSUE THREAD

**Issue by kaspar-allenbach** [enupal/translate#8]
### Description

I Installed the demoversion of your plugin via Plugin Store. But there is nothing showing up. Is this becaus I'm in demo mode? 

Shouldn't there now all tags with the filter `| t ` be displayed?

![bildschirmfoto 2018-09-19 um 10 18 45](https://user-images.githubusercontent.com/762213/45740380-7048c900-bbf5-11e8-82db-d3bd790d9af1.png)

### Steps to reproduce

1. Install the plugin
2. Have a few `{{ 'key' | t }}` in some of the templates.

### Additional info

- Craft version: 3.0.23.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugin version: 1.1.3

**Comment by andrelopez** [comment]
Hi @kaspar-allenbach 

Thanks for reaching out. Have you tried clicking the "Pending" filter in the sidebar menu?

**Comment by andrelopez** [comment]
Hi @kaspar-allenbach 

Any updates about this issue?

**Comment by kaspar-allenbach** [comment]
Nope. Nothing is happening.

Everywhere I click I get a «Unknown Error occured» at the top
![bildschirmfoto 2018-09-26 um 08 52 51](https://user-images.githubusercontent.com/762213/46062273-90ced100-c169-11e8-9536-16f0e254837b.png)

**Comment by kaspar-allenbach** [comment]
I get this in the error log:

`2018-09-26 09:03:31 [-][1][-][error][TypeError] TypeError: Argument 1 passed to craft\services\TemplateCaches::includeElementInTemplateCaches() must be of the type integer, string given, called in /path/vendor/craftcms/cms/src/helpers/Template.php on line 176 and defined in /path/vendor/craftcms/cms/src/services/TemplateCaches.php:248`

Does this have anything to do with it, or is this unrelated?

**Comment by andrelopez** [comment]
Thanks for following up.

Could you please try clear caches? in your Craft CMS dashboard go to Utilities->Clear caches-> All 

If the error persists could you please clean the craft log file at storage/logs/web.log and recreate the issue and then send back to us the log file to support@enupal.com ?

Thank you

**Comment by kaspar-allenbach** [comment]
sent you an email

**Comment by andrelopez** [comment]
Hi @kaspar-allenbach 

Could you please update your plugin to version 1.1.5 and let me know if the issue is solved?

Best,

**Comment by kaspar-allenbach** [comment]
Hi. Yes I will. I'm sorry I have a huge workload right now.

**Comment by andrelopez** [comment]
No problem @kaspar-allenbach other user with the same error just confirmed us that the issue was solved.

Best,

**Comment by kaspar-allenbach** [comment]
okay. I've updated everything. Now the things show up 👌
